from pydantic import BaseModel, Field
from enum import Enum
from datetime import datetime
from typing import Optional


class ModelName(str, Enum):
    GEMINI_2_5_FLASH = "gemini-2.5-flash"
    GEMINI_2_5_FLASH_LITE = "gemini-2.5-flash-lite"


class QueryInput(BaseModel):
    question: str = Field(
        ...,
        description="The question to be answered."
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Unique session identifier. If not provided, one will be generated."
    )
    model: ModelName = Field(
        default=ModelName.GEMINI_2_5_FLASH,
        description="The language model to use."
    )


class QueryResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The answer generated by the language model."
    )
    session_id: str = Field(
        ...,
        description="Unique identifier for the session."
    )
    model: ModelName = Field(
        ...,
        description="The language model used to generate the answer."
    )


class DocumentInfo(BaseModel):
    id: int = Field(..., description="Unique document ID.")
    filename: str = Field(..., description="Name of the uploaded file.")
    upload_timestamp: datetime = Field(
        ...,
        description="Timestamp when the file was uploaded."
    )


class DeleteFileRequest(BaseModel):
    file_id: int = Field(..., description="ID of the file to delete.")